### PR TITLE
#sum dc pipline 2022

### PR DESCRIPTION
**Pull request by eburton9**
@ptatian Here is how I was summing the 0-30% AMI units from the dataset. If the row has Proportional_HPTF_30_AMI var then count the units in units_0_to_30 var.

### CODE REVIEW

**Comment by ptatian** [comment]
@eburton9 You'll need to look at the data set to confirm how it is structured. The variable units_0_to_30 would seem to cover all the units in a project, which could be more than just HPTF. There is also a hptf_30_ami_unit_cost field. You might want to compare the two.

**Comment by eburton9** [comment]
@ptatian I didn’t see any variable that had just HPTF unit count. Should we instead give a $ amount based on hptf_30_ami_unit_cost?

**Comment by ptatian** [comment]
Ok. I’m not very fluent on this file, to be honest. I’ll take a closer look later today.
________________________________

**Comment by ptatian** [comment]
@eburton9 I think what you did was a reasonable approach. As you noted, there were no specific counts of HPTF units, so taking the 0-30 AMI count for those projects with HPTF investment seems OK to me. The only suggestions I might make are excluding units where the Proportional_HPTF_30_AMI is zero (0) or where Loan_Status is Withdrawn.

**Pull request merged**
