### PR TITLE
update gross rent program to include 2017 ACS 1 year estimate

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo 2018 1 year data is supposed to be released but I don't see it on the website so I only updated the program to include 2017 data for now. Let me know if I missed where to download 2018 data.

**Comment by maggiesu0725** [comment]
@rpitingolo following up on this.

**Comment by rpitingolo** [comment]
@maggiesu0725 did you download it from American Factfinder? Census is transitioning to data.census.gov - i did a quick search and it looks like B25063 for 2018 is there.

**Comment by maggiesu0725** [comment]
@rpitingolo wow the new website is really cool. Program and data updated to 2018. Ready for review.

**Comment by rpitingolo** [comment]
@maggiesu0725 thanks. My SAS is down at the moment but hopefully Help Desk can get me back up soon. I'll review then.

**Comment by rpitingolo** [comment]
@maggiesu0725 there is an extra blank line in the datalines section between the last row of data and the semicolon. It's causing the final CSV to look weird. Remove that line and it should be good to go.

**Comment by maggiesu0725** [comment]
@rpitingolo ready to merge

**Comment by rpitingolo** [comment]
@maggiesu0725 OK, go ahead and finalize this one. Thanks!

**Pull request merged**
