### PR TITLE
churches request

### PR DESCRIPTION
**Pull request by lhendey**
initial code for creating ownercat on black knight data. didn't yet update format.

### CODE REVIEW

**Comment by sstrochak** [comment]
@lhendey do you want to take a look at what I did for Arlington and make sure I am on the right track before I repeat for other jurisdictions?

**Comment by lhendey** [comment]
@sstrochak will try. just got new computer and need to figure how to sync github again.

**Comment by sstrochak** [comment]
@lhendey feel free to stop by if that is easier!

**Comment by rpitingolo** [comment]
@lhendey let me know if you need help with github sync. I have fresh memories from getting our other staff set up on new PCs.

**Pull request merged**
